[book]
authors = ["Nicolas Mohnblatt"]
language = "en"
multilingual = true
src = "src"
title = "ZK Jargon Decoder"

[preprocessor.katex]
after = ["links"]

[preprocessor.gettext]
after = ["links"]

[output.html]
smart-punctuation = true
no-section-label = true
git-repository-url = "https://github.com/zkjargon/zkjargon.github.io/"
edit-url-template = "https://github.com/zkjargon/zkjargon.github.io/edit/main/{path}"

[output.html.print]
page-break = false

[build]
extra-watch-dirs = ["po"]
